### ISSUE TITLE
Allow user to connect multiple logins using Ceramic's 3ID - 3000$ (2000$ worth of G$ + 1000$ USDC) 

### ISSUE THREAD

**Issue by sirpy** [GoodDollar/Bounties#8]
### Motivation
Currently users' privatekey is accessible from a single social login. If for some reason the user is blocked from using that social login he is no longer able to access his wallet.
Connecting with multiple socials can allow for redundancy and also for more advanced 2FA security.

#### Getting started
Please read about our bounty mentorship program and join the telegram channel:
https://github.com/GoodDollar/Bounties

### Details
Use ceramic's 3ID solution to connect multiple accounts and store the main user privatekey encrypted with the 3ID encryption key

#### Part 1 - create a simple sdk on top of Ceramic 3ID. - 1000$
https://developers.ceramic.network/authentication/3id-did/lifecycle/
https://developers.ceramic.network/tools/self-id/write/
- [x] add method `initialize(privatekey)` 
    - should initialize a DID based on privatekey, create a new one if doesnt exists or fetch existing (ie `authSecret`)
    - should encrypt privatekey using the DID seed and store it in a field called `masterSeed` (can this be easily added to the profile?)
- [x] add method `addAuthenticator(privatekey)` - adds this as another `authSecret` that can access the DID seed. calling `initialize` with this new key should now also fetch the same DID
- [x] add method `getMasterSeed` - returns the decrypted master seed
- [x] add method `removeAuthenticator(privatekey)` - removes an authenticator

#### Part 2 - integrate with wallet - 500$
- [x] During login/signup authentication with Torus (`Authtorus.js`), once privatekey is received from Torus, call `initialize` and then get the master seed (`getMasterSeed`) use the master seed as the final privatekey used to login the user
- [ ] Upgrade existing wallets - add an update script in `lib/updates` (see existing ones on how to implement) that simply calls `initialize` with the current master seed

#### Part 3 - allow user to connect multiple accounts  - 1500$
- [x] add a new screen and route ConnectAccounts
- [x] show a list with existing login options (facebook, google, passwordless) and a toggle button next to each
- [x] the toggle button of existing socials that are already connected should be on. (by default at least one toggle should be on - ie the account user connected with)
- [ ] once user turns on a toggle button it triggers the Torus login flow.
    - Login flow is based on redirect, so need to store in localstorage that user started the account connect flow
    - Once user is redirected back to the wallet, need to check in localstorage if user started the flow and navigate back to the ConnectAccounts screen with the torus result
    - If torus login was completed successfully call `addAuthenticator` and set the relevant toggle button to on
    - if login failed show an error dialog
- [ ] once user turns off a toggle button, a confirmation popup is shown asking if the user is sure. if user confirms call `removeAuthenticator`

**Comment by gitcoinbot** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__This issue now has a funding of 15000000.0 G$ (3000.0 USD @ $0.0/G$)  attached to it as part of the GoodDollar fund.__

 * If you would like to work on this issue you can 'start work' [on the Gitcoin Issue Details page](https://gitcoin.co/issue/gooddollar/bounties/8/100027257).
* Want to chip in? Add your own contribution [here](https://gitcoin.co/issue/gooddollar/bounties/8/100027257).
* Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://discord.gg/gitcoin/'>Gitcoin's Discord</a>
* $5,694,628.62 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)

**Comment by gitcoinbot** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__Workers have applied to start work__.


These users each claimed they can complete the work by 264 years, 11 months from now.
Please review their action plans below:


**1) [sdmg15](https://gitcoin.co/sdmg15) has applied to start work _(Funders only: [approve worker](https://gitcoin.co/issue/gooddollar/bounties/8/100027257?mutate_worker_action=approve&worker=sdmg15) | [reject worker](https://gitcoin.co/issue/gooddollar/bounties/8/100027257?mutate_worker_action=reject&worker=sdmg15))_.**

I'll take over the Part 1 and create a simple sdk on top of Ceramic 3ID

Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/gooddollar/bounties/8/100027257).

**Comment by gitcoinbot** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__The funding of 15000000.0 G$  (3000.00 USD @ $0.0/G$) attached to this issue has been **cancelled** by the bounty submitter__

 
* Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://discord.gg/gitcoin/'>Gitcoin's Discord</a>
* $6,058,480.06 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)

**Comment by sirpy** [comment]
completed
